server:
  port: 3001

settings:
  url:
    brt-address: "http://localhost:3002/api/v1/brt/"
  broker:
    topic:
      billing-launch-topic: "t.billing.launch"
      update-report-data-topic: "t.report-data.update"
