server:
  port: 3002
settings:
  url:
    cdr-address: "http://localhost:3003/api/v1/cdr/"
    hsr-address: "http://localhost:3001/api/v1/hrs/"
  broker:
    topic:
      user-update-topic: "t.user.update"

spring:
  kafka:
    consumer:
      group-id: "default"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost/cdrsystem
    username: postgres
    password: 123456
